package org.svomz.fsmweb.domain;

import org.svomz.fsm.Event;

public enum LoanRequestEvent implements Event {
  ACCEPTED_BY_SCORING_SYSTEM,
  ACCEPTED_BY_HUMAN,
  REFUSED_BY_SCORING_SYSTEM,
  ABANDONNED_BY_CLIENT,
  UNKNOWN_SCORING,
  REFUSED_BY_HUMAN,
  EMPLOYER_INFORMATION_COLLECTED,
  ACCEPTED_BY_CRAKING_SYSTEM,
  REFUSED_BY_CRAKING_SYSTEM,
  MANUAL_SIGNING_CHOSEN,
  CONTRACT_PRINTED,
  CONTRACT_VALIDATED,
  DIGITAL_SIGNING_CHOSEN,
  CONTRACT_OPTIONS_CHOSEN,
  CLIENT_SIGNED,
  VENDOR_SIGNED,
  EVIDENCES_UPLOADED,
  TEMPORARY_CARD_NUMBER_ASSIGNED,
  TEMPORARY_CARD_RECEIPT_SIGNED,
  DIGITAL_SIGNED_ABANDONNED
}
